#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

// SoftDevice configuration
#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_PERIPHERAL_ENABLED 0
#define NRF_SDH_BLE_CENTRAL_ENABLED 1
#define NRF_SDH_BLE_GATT_ENABLED 1
#define NRF_SDH_BLE_GATTS_ENABLED 0
#define NRF_SDH_BLE_GATTC_ENABLED 1
#define NRF_SDH_BLE_L2CAP_ENABLED 1
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 23

// BLE Central configuration
#define NRF_SDH_BLE_CENTRAL_LINK_COUNT 1
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 0
#define NRF_SDH_BLE_TOTAL_LINK_COUNT 1

// BLE scanning configuration
#define NRF_SDH_BLE_SCAN_ENABLED 1
#define NRF_SDH_BLE_SCAN_PARAMS_ENABLED 1
#define NRF_SDH_BLE_SCAN_PARAMS_UPDATE_ENABLED 1

// BLE connection configuration
#define NRF_SDH_BLE_CONN_PARAMS_ENABLED 1
#define NRF_SDH_BLE_CONN_PARAMS_UPDATE_ENABLED 1

// USB configuration
#define NRFX_USBD_ENABLED 1
#define NRFX_USBD_CONFIG_IRQ_PRIORITY 6
#define NRFX_USBD_CONFIG_DMASCHEDULER_MODE 2
#define NRFX_USBD_CONFIG_ISO_IN_ZLP 0

// USB HID configuration
#define NRFX_USBD_CONFIG_EVENT_QUEUE_ENABLE 1
#define NRFX_USBD_CONFIG_EVENT_QUEUE_SIZE 32

// System configuration
#define NRF_SDH_ENABLED 1
#define NRF_SDH_SOC_ENABLED 1
#define NRF_SDH_CLOCK_ENABLED 1
#define NRF_SDH_CLOCK_LF_SRC 1
#define NRF_SDH_CLOCK_LF_RC_CTIV 16
#define NRF_SDH_CLOCK_LF_RC_TEMP_CTIV 2
#define NRF_SDH_CLOCK_LF_ACCURACY 7

// Logging configuration
#define NRF_LOG_ENABLED 1
#define NRF_LOG_BACKEND_UART_ENABLED 1
#define NRF_LOG_BACKEND_UART_TX_PIN 6
#define NRF_LOG_BACKEND_UART_BAUDRATE 115200
#define NRF_LOG_DEFAULT_LEVEL 3

// Timer configuration
#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER0_ENABLED 1

// GPIO configuration
#define NRFX_GPIOTE_ENABLED 1
#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4

// Power management
#define NRF_PWR_MGMT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_FPU_SUPPORT_ENABLED 1

// Memory configuration
#define NRF_SDH_BLE_GATTS_ATTR_TAB_SIZE 1408
#define NRF_SDH_BLE_GATTC_ATTR_TAB_SIZE 1408

// HID Service UUIDs (standard)
#define BLE_UUID_HID_SERVICE 0x1812
#define BLE_UUID_HID_INFORMATION_CHAR 0x2A4A
#define BLE_UUID_HID_REPORT_MAP_CHAR 0x2A4B
#define BLE_UUID_HID_CONTROL_POINT_CHAR 0x2A4C
#define BLE_UUID_HID_REPORT_CHAR 0x2A4D

// Nordic UART Service UUIDs
#define BLE_UUID_NUS_SERVICE 0x6E400001B5A3F393E0A9E50E24DCCA9E
#define BLE_UUID_NUS_TX_CHAR 0x6E400002B5A3F393E0A9E50E24DCCA9E
#define BLE_UUID_NUS_RX_CHAR 0x6E400003B5A3F393E0A9E50E24DCCA9E

// Application specific configuration
#define BLE_SCAN_INTERVAL 160  // 100ms
#define BLE_SCAN_WINDOW 80     // 50ms
#define BLE_SCAN_TIMEOUT 0     // No timeout
#define BLE_CONN_INTERVAL_MIN 6  // 7.5ms
#define BLE_CONN_INTERVAL_MAX 6  // 7.5ms
#define BLE_SLAVE_LATENCY 0
#define BLE_SUPERVISION_TIMEOUT 400  // 4s

// USB HID Report Descriptor (Generic HID)
#define USB_HID_REPORT_DESC_SIZE 52

// LED indicators
#define LED_BLE_CONNECTED 17
#define LED_USB_CONNECTED 18
#define LED_ERROR 19

#endif // SDK_CONFIG_H