manifest:
  version: 0.7
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nordicsemi
      url-base: https://github.com/nordicsemi
  projects:
    - name: zephyr
      revision: v3.4.0
      remote: zephyrproject-rtos
      path: zephyr
      import: true 