/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MOUTHWARE_MESSAGE_MOUTHPADUSB_PB_H_INCLUDED
#define PB_MOUTHWARE_MESSAGE_MOUTHPADUSB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _mouthware_message_MouthpadAppToUsbMessageDestination {
    mouthware_message_MouthpadAppToUsbMessageDestination_MOUTHPAD_USB_MESSAGE_DESTINATION_UNSPECIFIED = 0,
    mouthware_message_MouthpadAppToUsbMessageDestination_MOUTHPAD_USB_MESSAGE_DESTINATION_DONGLE = 1,
    mouthware_message_MouthpadAppToUsbMessageDestination_MOUTHPAD_USB_MESSAGE_DESTINATION_MOUTHPAD = 2
} mouthware_message_MouthpadAppToUsbMessageDestination;

typedef enum _mouthware_message_PassThroughToMouthpadErrorCode {
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNSPECIFIED = 0,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_TIMEOUT = 1,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_MESSAGE_TOO_LARGE = 2,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_MESSAGE_NOT_CONNECTED = 3,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNKNOWN_ERROR = 4,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE = 5
} mouthware_message_PassThroughToMouthpadErrorCode;

typedef enum _mouthware_message_UsbDongleConnectionStatus {
    mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_UNSPECIFIED = 0,
    mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_DISCONNECTED = 1,
    mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_CONNECTED = 2,
    mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_SEARCHING = 3,
    mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_CONNECTING = 4
} mouthware_message_UsbDongleConnectionStatus;

typedef enum _mouthware_message_BLEConnectionCommandType {
    mouthware_message_BLEConnectionCommandType_BLE_CONNECTION_COMMAND_UNSPECIFIED = 0,
    mouthware_message_BLEConnectionCommandType_BLE_CONNECTION_COMMAND_CONNECT = 1,
    mouthware_message_BLEConnectionCommandType_BLE_CONNECTION_COMMAND_DISCONNECT = 2
} mouthware_message_BLEConnectionCommandType;

typedef enum _mouthware_message_BLEConnectionStatus {
    mouthware_message_BLEConnectionStatus_BLE_CONNECTION_STATUS_UNSPECIFIED = 0,
    mouthware_message_BLEConnectionStatus_BLE_CONNECTION_STATUS_CONNECTED = 1,
    mouthware_message_BLEConnectionStatus_BLE_CONNECTION_STATUS_DISCONNECTED = 2
} mouthware_message_BLEConnectionStatus;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(240) mouthware_message_PassThroughToMouthpad_data_t;
typedef struct _mouthware_message_PassThroughToMouthpad {
    mouthware_message_PassThroughToMouthpad_data_t data;
} mouthware_message_PassThroughToMouthpad;

typedef struct _mouthware_message_PassThroughToMouthpadResponse {
    mouthware_message_PassThroughToMouthpadErrorCode error_code;
} mouthware_message_PassThroughToMouthpadResponse;

typedef PB_BYTES_ARRAY_T(255) mouthware_message_PassThroughToApp_data_t;
typedef struct _mouthware_message_PassThroughToApp {
    mouthware_message_PassThroughToApp_data_t data;
} mouthware_message_PassThroughToApp;

typedef struct _mouthware_message_ConnectionStatusRequest {
    char dummy_field;
} mouthware_message_ConnectionStatusRequest;

typedef struct _mouthware_message_ConnectionStatus {
    mouthware_message_UsbDongleConnectionStatus connection_status;
} mouthware_message_ConnectionStatus;

typedef struct _mouthware_message_RSSIRequest {
    char dummy_field;
} mouthware_message_RSSIRequest;

typedef struct _mouthware_message_RSSIStatus {
    int32_t rssi;
} mouthware_message_RSSIStatus;

typedef struct _mouthware_message_BLEConnectionCommand {
    mouthware_message_BLEConnectionCommandType command;
    pb_callback_t mac_address;
} mouthware_message_BLEConnectionCommand;

typedef struct _mouthware_message_MouthpadAppToUsbMessage {
    mouthware_message_MouthpadAppToUsbMessageDestination destination;
    pb_size_t which_message_body;
    union _mouthware_message_MouthpadAppToUsbMessage_message_body {
        mouthware_message_BLEConnectionCommand ble_connection_command;
        mouthware_message_ConnectionStatusRequest connection_status_request;
        mouthware_message_RSSIRequest rssi_request;
        mouthware_message_PassThroughToMouthpad pass_through_to_mouthpad;
    } message_body;
} mouthware_message_MouthpadAppToUsbMessage;

typedef struct _mouthware_message_BLEConnectionCommandResponse {
    mouthware_message_BLEConnectionCommandType command;
    pb_callback_t mac_address;
} mouthware_message_BLEConnectionCommandResponse;

typedef struct _mouthware_message_UsbDongleToMouthpadAppMessage {
    pb_size_t which_message_body;
    union _mouthware_message_UsbDongleToMouthpadAppMessage_message_body {
        mouthware_message_BLEConnectionCommandResponse ble_connection_command_response;
        mouthware_message_ConnectionStatus connection_status;
        mouthware_message_RSSIStatus rssi_status;
        mouthware_message_PassThroughToMouthpadResponse pass_through_to_mouthpad_response;
        mouthware_message_PassThroughToApp pass_through_to_app;
    } message_body;
} mouthware_message_UsbDongleToMouthpadAppMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _mouthware_message_MouthpadAppToUsbMessageDestination_MIN mouthware_message_MouthpadAppToUsbMessageDestination_MOUTHPAD_USB_MESSAGE_DESTINATION_UNSPECIFIED
#define _mouthware_message_MouthpadAppToUsbMessageDestination_MAX mouthware_message_MouthpadAppToUsbMessageDestination_MOUTHPAD_USB_MESSAGE_DESTINATION_MOUTHPAD
#define _mouthware_message_MouthpadAppToUsbMessageDestination_ARRAYSIZE ((mouthware_message_MouthpadAppToUsbMessageDestination)(mouthware_message_MouthpadAppToUsbMessageDestination_MOUTHPAD_USB_MESSAGE_DESTINATION_MOUTHPAD+1))

#define _mouthware_message_PassThroughToMouthpadErrorCode_MIN mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNSPECIFIED
#define _mouthware_message_PassThroughToMouthpadErrorCode_MAX mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE
#define _mouthware_message_PassThroughToMouthpadErrorCode_ARRAYSIZE ((mouthware_message_PassThroughToMouthpadErrorCode)(mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE+1))

#define _mouthware_message_UsbDongleConnectionStatus_MIN mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_UNSPECIFIED
#define _mouthware_message_UsbDongleConnectionStatus_MAX mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_CONNECTING
#define _mouthware_message_UsbDongleConnectionStatus_ARRAYSIZE ((mouthware_message_UsbDongleConnectionStatus)(mouthware_message_UsbDongleConnectionStatus_USB_DONGLE_CONNECTION_STATUS_CONNECTING+1))

#define _mouthware_message_BLEConnectionCommandType_MIN mouthware_message_BLEConnectionCommandType_BLE_CONNECTION_COMMAND_UNSPECIFIED
#define _mouthware_message_BLEConnectionCommandType_MAX mouthware_message_BLEConnectionCommandType_BLE_CONNECTION_COMMAND_DISCONNECT
#define _mouthware_message_BLEConnectionCommandType_ARRAYSIZE ((mouthware_message_BLEConnectionCommandType)(mouthware_message_BLEConnectionCommandType_BLE_CONNECTION_COMMAND_DISCONNECT+1))

#define _mouthware_message_BLEConnectionStatus_MIN mouthware_message_BLEConnectionStatus_BLE_CONNECTION_STATUS_UNSPECIFIED
#define _mouthware_message_BLEConnectionStatus_MAX mouthware_message_BLEConnectionStatus_BLE_CONNECTION_STATUS_DISCONNECTED
#define _mouthware_message_BLEConnectionStatus_ARRAYSIZE ((mouthware_message_BLEConnectionStatus)(mouthware_message_BLEConnectionStatus_BLE_CONNECTION_STATUS_DISCONNECTED+1))


#define mouthware_message_MouthpadAppToUsbMessage_destination_ENUMTYPE mouthware_message_MouthpadAppToUsbMessageDestination

#define mouthware_message_PassThroughToMouthpadResponse_error_code_ENUMTYPE mouthware_message_PassThroughToMouthpadErrorCode




#define mouthware_message_ConnectionStatus_connection_status_ENUMTYPE mouthware_message_UsbDongleConnectionStatus



#define mouthware_message_BLEConnectionCommand_command_ENUMTYPE mouthware_message_BLEConnectionCommandType

#define mouthware_message_BLEConnectionCommandResponse_command_ENUMTYPE mouthware_message_BLEConnectionCommandType


/* Initializer values for message structs */
#define mouthware_message_PassThroughToMouthpad_init_default {{0, {0}}}
#define mouthware_message_MouthpadAppToUsbMessage_init_default {_mouthware_message_MouthpadAppToUsbMessageDestination_MIN, 0, {mouthware_message_BLEConnectionCommand_init_default}}
#define mouthware_message_PassThroughToMouthpadResponse_init_default {_mouthware_message_PassThroughToMouthpadErrorCode_MIN}
#define mouthware_message_PassThroughToApp_init_default {{0, {0}}}
#define mouthware_message_UsbDongleToMouthpadAppMessage_init_default {0, {mouthware_message_BLEConnectionCommandResponse_init_default}}
#define mouthware_message_ConnectionStatusRequest_init_default {0}
#define mouthware_message_ConnectionStatus_init_default {_mouthware_message_UsbDongleConnectionStatus_MIN}
#define mouthware_message_RSSIRequest_init_default {0}
#define mouthware_message_RSSIStatus_init_default {0}
#define mouthware_message_BLEConnectionCommand_init_default {_mouthware_message_BLEConnectionCommandType_MIN, {{NULL}, NULL}}
#define mouthware_message_BLEConnectionCommandResponse_init_default {_mouthware_message_BLEConnectionCommandType_MIN, {{NULL}, NULL}}
#define mouthware_message_PassThroughToMouthpad_init_zero {{0, {0}}}
#define mouthware_message_MouthpadAppToUsbMessage_init_zero {_mouthware_message_MouthpadAppToUsbMessageDestination_MIN, 0, {mouthware_message_BLEConnectionCommand_init_zero}}
#define mouthware_message_PassThroughToMouthpadResponse_init_zero {_mouthware_message_PassThroughToMouthpadErrorCode_MIN}
#define mouthware_message_PassThroughToApp_init_zero {{0, {0}}}
#define mouthware_message_UsbDongleToMouthpadAppMessage_init_zero {0, {mouthware_message_BLEConnectionCommandResponse_init_zero}}
#define mouthware_message_ConnectionStatusRequest_init_zero {0}
#define mouthware_message_ConnectionStatus_init_zero {_mouthware_message_UsbDongleConnectionStatus_MIN}
#define mouthware_message_RSSIRequest_init_zero  {0}
#define mouthware_message_RSSIStatus_init_zero   {0}
#define mouthware_message_BLEConnectionCommand_init_zero {_mouthware_message_BLEConnectionCommandType_MIN, {{NULL}, NULL}}
#define mouthware_message_BLEConnectionCommandResponse_init_zero {_mouthware_message_BLEConnectionCommandType_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define mouthware_message_PassThroughToMouthpad_data_tag 1
#define mouthware_message_PassThroughToMouthpadResponse_error_code_tag 1
#define mouthware_message_PassThroughToApp_data_tag 1
#define mouthware_message_ConnectionStatus_connection_status_tag 1
#define mouthware_message_RSSIStatus_rssi_tag    1
#define mouthware_message_BLEConnectionCommand_command_tag 1
#define mouthware_message_BLEConnectionCommand_mac_address_tag 2
#define mouthware_message_MouthpadAppToUsbMessage_destination_tag 1
#define mouthware_message_MouthpadAppToUsbMessage_ble_connection_command_tag 2
#define mouthware_message_MouthpadAppToUsbMessage_connection_status_request_tag 3
#define mouthware_message_MouthpadAppToUsbMessage_rssi_request_tag 4
#define mouthware_message_MouthpadAppToUsbMessage_pass_through_to_mouthpad_tag 5
#define mouthware_message_BLEConnectionCommandResponse_command_tag 1
#define mouthware_message_BLEConnectionCommandResponse_mac_address_tag 2
#define mouthware_message_UsbDongleToMouthpadAppMessage_ble_connection_command_response_tag 1
#define mouthware_message_UsbDongleToMouthpadAppMessage_connection_status_tag 2
#define mouthware_message_UsbDongleToMouthpadAppMessage_rssi_status_tag 3
#define mouthware_message_UsbDongleToMouthpadAppMessage_pass_through_to_mouthpad_response_tag 4
#define mouthware_message_UsbDongleToMouthpadAppMessage_pass_through_to_app_tag 5

/* Struct field encoding specification for nanopb */
#define mouthware_message_PassThroughToMouthpad_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define mouthware_message_PassThroughToMouthpad_CALLBACK NULL
#define mouthware_message_PassThroughToMouthpad_DEFAULT NULL

#define mouthware_message_MouthpadAppToUsbMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    destination,       1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,ble_connection_command,message_body.ble_connection_command),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,connection_status_request,message_body.connection_status_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,rssi_request,message_body.rssi_request),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_mouthpad,message_body.pass_through_to_mouthpad),   5)
#define mouthware_message_MouthpadAppToUsbMessage_CALLBACK NULL
#define mouthware_message_MouthpadAppToUsbMessage_DEFAULT NULL
#define mouthware_message_MouthpadAppToUsbMessage_message_body_ble_connection_command_MSGTYPE mouthware_message_BLEConnectionCommand
#define mouthware_message_MouthpadAppToUsbMessage_message_body_connection_status_request_MSGTYPE mouthware_message_ConnectionStatusRequest
#define mouthware_message_MouthpadAppToUsbMessage_message_body_rssi_request_MSGTYPE mouthware_message_RSSIRequest
#define mouthware_message_MouthpadAppToUsbMessage_message_body_pass_through_to_mouthpad_MSGTYPE mouthware_message_PassThroughToMouthpad

#define mouthware_message_PassThroughToMouthpadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        1)
#define mouthware_message_PassThroughToMouthpadResponse_CALLBACK NULL
#define mouthware_message_PassThroughToMouthpadResponse_DEFAULT NULL

#define mouthware_message_PassThroughToApp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define mouthware_message_PassThroughToApp_CALLBACK NULL
#define mouthware_message_PassThroughToApp_DEFAULT NULL

#define mouthware_message_UsbDongleToMouthpadAppMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,ble_connection_command_response,message_body.ble_connection_command_response),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,connection_status,message_body.connection_status),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,rssi_status,message_body.rssi_status),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_mouthpad_response,message_body.pass_through_to_mouthpad_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_app,message_body.pass_through_to_app),   5)
#define mouthware_message_UsbDongleToMouthpadAppMessage_CALLBACK NULL
#define mouthware_message_UsbDongleToMouthpadAppMessage_DEFAULT NULL
#define mouthware_message_UsbDongleToMouthpadAppMessage_message_body_ble_connection_command_response_MSGTYPE mouthware_message_BLEConnectionCommandResponse
#define mouthware_message_UsbDongleToMouthpadAppMessage_message_body_connection_status_MSGTYPE mouthware_message_ConnectionStatus
#define mouthware_message_UsbDongleToMouthpadAppMessage_message_body_rssi_status_MSGTYPE mouthware_message_RSSIStatus
#define mouthware_message_UsbDongleToMouthpadAppMessage_message_body_pass_through_to_mouthpad_response_MSGTYPE mouthware_message_PassThroughToMouthpadResponse
#define mouthware_message_UsbDongleToMouthpadAppMessage_message_body_pass_through_to_app_MSGTYPE mouthware_message_PassThroughToApp

#define mouthware_message_ConnectionStatusRequest_FIELDLIST(X, a) \

#define mouthware_message_ConnectionStatusRequest_CALLBACK NULL
#define mouthware_message_ConnectionStatusRequest_DEFAULT NULL

#define mouthware_message_ConnectionStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    connection_status,   1)
#define mouthware_message_ConnectionStatus_CALLBACK NULL
#define mouthware_message_ConnectionStatus_DEFAULT NULL

#define mouthware_message_RSSIRequest_FIELDLIST(X, a) \

#define mouthware_message_RSSIRequest_CALLBACK NULL
#define mouthware_message_RSSIRequest_DEFAULT NULL

#define mouthware_message_RSSIStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              1)
#define mouthware_message_RSSIStatus_CALLBACK NULL
#define mouthware_message_RSSIStatus_DEFAULT NULL

#define mouthware_message_BLEConnectionCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   mac_address,       2)
#define mouthware_message_BLEConnectionCommand_CALLBACK pb_default_field_callback
#define mouthware_message_BLEConnectionCommand_DEFAULT NULL

#define mouthware_message_BLEConnectionCommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   mac_address,       2)
#define mouthware_message_BLEConnectionCommandResponse_CALLBACK pb_default_field_callback
#define mouthware_message_BLEConnectionCommandResponse_DEFAULT NULL

extern const pb_msgdesc_t mouthware_message_PassThroughToMouthpad_msg;
extern const pb_msgdesc_t mouthware_message_MouthpadAppToUsbMessage_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToMouthpadResponse_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToApp_msg;
extern const pb_msgdesc_t mouthware_message_UsbDongleToMouthpadAppMessage_msg;
extern const pb_msgdesc_t mouthware_message_ConnectionStatusRequest_msg;
extern const pb_msgdesc_t mouthware_message_ConnectionStatus_msg;
extern const pb_msgdesc_t mouthware_message_RSSIRequest_msg;
extern const pb_msgdesc_t mouthware_message_RSSIStatus_msg;
extern const pb_msgdesc_t mouthware_message_BLEConnectionCommand_msg;
extern const pb_msgdesc_t mouthware_message_BLEConnectionCommandResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define mouthware_message_PassThroughToMouthpad_fields &mouthware_message_PassThroughToMouthpad_msg
#define mouthware_message_MouthpadAppToUsbMessage_fields &mouthware_message_MouthpadAppToUsbMessage_msg
#define mouthware_message_PassThroughToMouthpadResponse_fields &mouthware_message_PassThroughToMouthpadResponse_msg
#define mouthware_message_PassThroughToApp_fields &mouthware_message_PassThroughToApp_msg
#define mouthware_message_UsbDongleToMouthpadAppMessage_fields &mouthware_message_UsbDongleToMouthpadAppMessage_msg
#define mouthware_message_ConnectionStatusRequest_fields &mouthware_message_ConnectionStatusRequest_msg
#define mouthware_message_ConnectionStatus_fields &mouthware_message_ConnectionStatus_msg
#define mouthware_message_RSSIRequest_fields &mouthware_message_RSSIRequest_msg
#define mouthware_message_RSSIStatus_fields &mouthware_message_RSSIStatus_msg
#define mouthware_message_BLEConnectionCommand_fields &mouthware_message_BLEConnectionCommand_msg
#define mouthware_message_BLEConnectionCommandResponse_fields &mouthware_message_BLEConnectionCommandResponse_msg

/* Maximum encoded size of messages (where known) */
/* mouthware_message_MouthpadAppToUsbMessage_size depends on runtime parameters */
/* mouthware_message_UsbDongleToMouthpadAppMessage_size depends on runtime parameters */
/* mouthware_message_BLEConnectionCommand_size depends on runtime parameters */
/* mouthware_message_BLEConnectionCommandResponse_size depends on runtime parameters */
#define MOUTHWARE_MESSAGE_MOUTHPADUSB_PB_H_MAX_SIZE mouthware_message_PassThroughToApp_size
#define mouthware_message_ConnectionStatusRequest_size 0
#define mouthware_message_ConnectionStatus_size  2
#define mouthware_message_PassThroughToApp_size  258
#define mouthware_message_PassThroughToMouthpadResponse_size 2
#define mouthware_message_PassThroughToMouthpad_size 243
#define mouthware_message_RSSIRequest_size       0
#define mouthware_message_RSSIStatus_size        11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
