/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "MouthpadUsb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mouthware_message_ConnectionStatusRequest, mouthware_message_ConnectionStatusRequest, AUTO)


PB_BIND(mouthware_message_RSSIRequest, mouthware_message_RSSIRequest, AUTO)


PB_BIND(mouthware_message_BLEConnectionCommand, mouthware_message_BLEConnectionCommand, AUTO)


PB_BIND(mouthware_message_PassThroughToMouthpadRequest, mouthware_message_PassThroughToMouthpadRequest, AUTO)


PB_BIND(mouthware_message_PassThroughToMouthpadResponse, mouthware_message_PassThroughToMouthpadResponse, AUTO)


PB_BIND(mouthware_message_PassThroughToApp, mouthware_message_PassThroughToApp, 2)


PB_BIND(mouthware_message_MouthpadAppToUsbMessage, mouthware_message_MouthpadAppToUsbMessage, AUTO)


PB_BIND(mouthware_message_ConnectionStatusResponse, mouthware_message_ConnectionStatusResponse, AUTO)


PB_BIND(mouthware_message_RSSIStatusResponse, mouthware_message_RSSIStatusResponse, AUTO)


PB_BIND(mouthware_message_BLEConnectionCommandResponse, mouthware_message_BLEConnectionCommandResponse, AUTO)


PB_BIND(mouthware_message_UsbDongleToMouthpadAppMessage, mouthware_message_UsbDongleToMouthpadAppMessage, 2)











