/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MOUTHWARE_MESSAGE_MOUTHPADRELAY_PB_H_INCLUDED
#define PB_MOUTHWARE_MESSAGE_MOUTHPADRELAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _mouthware_message_AppToRelayMessageDestination {
    mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_UNSPECIFIED = 0,
    mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_RELAY = 1,
    mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_MOUTHPAD = 2
} mouthware_message_AppToRelayMessageDestination;

typedef enum _mouthware_message_RelayBleConnectionStatus {
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_UNSPECIFIED = 0,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_DISCONNECTED = 1,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTED = 2,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_SEARCHING = 3,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTING = 4
} mouthware_message_RelayBleConnectionStatus;

typedef enum _mouthware_message_PassThroughToMouthpadErrorCode {
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNSPECIFIED = 0,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_TIMEOUT = 1,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_MESSAGE_TOO_LARGE = 2,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_MESSAGE_NOT_CONNECTED = 3,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNKNOWN_ERROR = 4,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE = 5
} mouthware_message_PassThroughToMouthpadErrorCode;

/* Struct definitions */
typedef struct _mouthware_message_BleConnectionStatusRead {
    char dummy_field;
} mouthware_message_BleConnectionStatusRead;

typedef PB_BYTES_ARRAY_T(240) mouthware_message_PassThroughToMouthpad_data_t;
typedef struct _mouthware_message_PassThroughToMouthpad {
    mouthware_message_PassThroughToMouthpad_data_t data;
} mouthware_message_PassThroughToMouthpad;

/* / Message from App to the MouthPad Relay. */
typedef struct _mouthware_message_AppToRelayMessage {
    /* / The intended destination for the wrapped message. */
    mouthware_message_AppToRelayMessageDestination destination;
    pb_size_t which_message_body;
    union _mouthware_message_AppToRelayMessage_message_body {
        /* / Request information from the relay regarding current BLE connection status */
        mouthware_message_BleConnectionStatusRead ble_connection_status_read;
        /* / Message to forward to the MouthPad through the Relay. */
        mouthware_message_PassThroughToMouthpad pass_through_to_mouthpad;
    } message_body;
} mouthware_message_AppToRelayMessage;

typedef struct _mouthware_message_BleConnectionStatusResponse {
    mouthware_message_RelayBleConnectionStatus connection_status;
    int32_t rssi;
} mouthware_message_BleConnectionStatusResponse;

typedef struct _mouthware_message_PassThroughToMouthpadResponse {
    mouthware_message_PassThroughToMouthpadErrorCode error_code;
} mouthware_message_PassThroughToMouthpadResponse;

typedef PB_BYTES_ARRAY_T(255) mouthware_message_PassThroughToApp_data_t;
typedef struct _mouthware_message_PassThroughToApp {
    mouthware_message_PassThroughToApp_data_t data;
} mouthware_message_PassThroughToApp;

/* / Message from the MouthPad Relay to the App. */
typedef struct _mouthware_message_RelayToAppMessage {
    pb_size_t which_message_body;
    union _mouthware_message_RelayToAppMessage_message_body {
        /* / Response to a BleConnectionStatusRead */
        mouthware_message_BleConnectionStatusResponse ble_connection_status_response;
        /* / Response to a PassThroughToMouthPadRequest (originating at the MouthPad). */
        mouthware_message_PassThroughToMouthpadResponse pass_through_to_mouthpad_response;
        /* / Message from the MouthPad for the app. */
        mouthware_message_PassThroughToApp pass_through_to_app;
    } message_body;
} mouthware_message_RelayToAppMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _mouthware_message_AppToRelayMessageDestination_MIN mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_UNSPECIFIED
#define _mouthware_message_AppToRelayMessageDestination_MAX mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_MOUTHPAD
#define _mouthware_message_AppToRelayMessageDestination_ARRAYSIZE ((mouthware_message_AppToRelayMessageDestination)(mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_MOUTHPAD+1))

#define _mouthware_message_RelayBleConnectionStatus_MIN mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_UNSPECIFIED
#define _mouthware_message_RelayBleConnectionStatus_MAX mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTING
#define _mouthware_message_RelayBleConnectionStatus_ARRAYSIZE ((mouthware_message_RelayBleConnectionStatus)(mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTING+1))

#define _mouthware_message_PassThroughToMouthpadErrorCode_MIN mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNSPECIFIED
#define _mouthware_message_PassThroughToMouthpadErrorCode_MAX mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE
#define _mouthware_message_PassThroughToMouthpadErrorCode_ARRAYSIZE ((mouthware_message_PassThroughToMouthpadErrorCode)(mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE+1))



#define mouthware_message_AppToRelayMessage_destination_ENUMTYPE mouthware_message_AppToRelayMessageDestination

#define mouthware_message_BleConnectionStatusResponse_connection_status_ENUMTYPE mouthware_message_RelayBleConnectionStatus

#define mouthware_message_PassThroughToMouthpadResponse_error_code_ENUMTYPE mouthware_message_PassThroughToMouthpadErrorCode




/* Initializer values for message structs */
#define mouthware_message_BleConnectionStatusRead_init_default {0}
#define mouthware_message_PassThroughToMouthpad_init_default {{0, {0}}}
#define mouthware_message_AppToRelayMessage_init_default {_mouthware_message_AppToRelayMessageDestination_MIN, 0, {mouthware_message_BleConnectionStatusRead_init_default}}
#define mouthware_message_BleConnectionStatusResponse_init_default {_mouthware_message_RelayBleConnectionStatus_MIN, 0}
#define mouthware_message_PassThroughToMouthpadResponse_init_default {_mouthware_message_PassThroughToMouthpadErrorCode_MIN}
#define mouthware_message_PassThroughToApp_init_default {{0, {0}}}
#define mouthware_message_RelayToAppMessage_init_default {0, {mouthware_message_BleConnectionStatusResponse_init_default}}
#define mouthware_message_BleConnectionStatusRead_init_zero {0}
#define mouthware_message_PassThroughToMouthpad_init_zero {{0, {0}}}
#define mouthware_message_AppToRelayMessage_init_zero {_mouthware_message_AppToRelayMessageDestination_MIN, 0, {mouthware_message_BleConnectionStatusRead_init_zero}}
#define mouthware_message_BleConnectionStatusResponse_init_zero {_mouthware_message_RelayBleConnectionStatus_MIN, 0}
#define mouthware_message_PassThroughToMouthpadResponse_init_zero {_mouthware_message_PassThroughToMouthpadErrorCode_MIN}
#define mouthware_message_PassThroughToApp_init_zero {{0, {0}}}
#define mouthware_message_RelayToAppMessage_init_zero {0, {mouthware_message_BleConnectionStatusResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define mouthware_message_PassThroughToMouthpad_data_tag 1
#define mouthware_message_AppToRelayMessage_destination_tag 1
#define mouthware_message_AppToRelayMessage_ble_connection_status_read_tag 2
#define mouthware_message_AppToRelayMessage_pass_through_to_mouthpad_tag 3
#define mouthware_message_BleConnectionStatusResponse_connection_status_tag 1
#define mouthware_message_BleConnectionStatusResponse_rssi_tag 2
#define mouthware_message_PassThroughToMouthpadResponse_error_code_tag 1
#define mouthware_message_PassThroughToApp_data_tag 1
#define mouthware_message_RelayToAppMessage_ble_connection_status_response_tag 1
#define mouthware_message_RelayToAppMessage_pass_through_to_mouthpad_response_tag 2
#define mouthware_message_RelayToAppMessage_pass_through_to_app_tag 3

/* Struct field encoding specification for nanopb */
#define mouthware_message_BleConnectionStatusRead_FIELDLIST(X, a) \

#define mouthware_message_BleConnectionStatusRead_CALLBACK NULL
#define mouthware_message_BleConnectionStatusRead_DEFAULT NULL

#define mouthware_message_PassThroughToMouthpad_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define mouthware_message_PassThroughToMouthpad_CALLBACK NULL
#define mouthware_message_PassThroughToMouthpad_DEFAULT NULL

#define mouthware_message_AppToRelayMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    destination,       1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,ble_connection_status_read,message_body.ble_connection_status_read),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_mouthpad,message_body.pass_through_to_mouthpad),   3)
#define mouthware_message_AppToRelayMessage_CALLBACK NULL
#define mouthware_message_AppToRelayMessage_DEFAULT NULL
#define mouthware_message_AppToRelayMessage_message_body_ble_connection_status_read_MSGTYPE mouthware_message_BleConnectionStatusRead
#define mouthware_message_AppToRelayMessage_message_body_pass_through_to_mouthpad_MSGTYPE mouthware_message_PassThroughToMouthpad

#define mouthware_message_BleConnectionStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    connection_status,   1) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              2)
#define mouthware_message_BleConnectionStatusResponse_CALLBACK NULL
#define mouthware_message_BleConnectionStatusResponse_DEFAULT NULL

#define mouthware_message_PassThroughToMouthpadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        1)
#define mouthware_message_PassThroughToMouthpadResponse_CALLBACK NULL
#define mouthware_message_PassThroughToMouthpadResponse_DEFAULT NULL

#define mouthware_message_PassThroughToApp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define mouthware_message_PassThroughToApp_CALLBACK NULL
#define mouthware_message_PassThroughToApp_DEFAULT NULL

#define mouthware_message_RelayToAppMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,ble_connection_status_response,message_body.ble_connection_status_response),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_mouthpad_response,message_body.pass_through_to_mouthpad_response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_app,message_body.pass_through_to_app),   3)
#define mouthware_message_RelayToAppMessage_CALLBACK NULL
#define mouthware_message_RelayToAppMessage_DEFAULT NULL
#define mouthware_message_RelayToAppMessage_message_body_ble_connection_status_response_MSGTYPE mouthware_message_BleConnectionStatusResponse
#define mouthware_message_RelayToAppMessage_message_body_pass_through_to_mouthpad_response_MSGTYPE mouthware_message_PassThroughToMouthpadResponse
#define mouthware_message_RelayToAppMessage_message_body_pass_through_to_app_MSGTYPE mouthware_message_PassThroughToApp

extern const pb_msgdesc_t mouthware_message_BleConnectionStatusRead_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToMouthpad_msg;
extern const pb_msgdesc_t mouthware_message_AppToRelayMessage_msg;
extern const pb_msgdesc_t mouthware_message_BleConnectionStatusResponse_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToMouthpadResponse_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToApp_msg;
extern const pb_msgdesc_t mouthware_message_RelayToAppMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define mouthware_message_BleConnectionStatusRead_fields &mouthware_message_BleConnectionStatusRead_msg
#define mouthware_message_PassThroughToMouthpad_fields &mouthware_message_PassThroughToMouthpad_msg
#define mouthware_message_AppToRelayMessage_fields &mouthware_message_AppToRelayMessage_msg
#define mouthware_message_BleConnectionStatusResponse_fields &mouthware_message_BleConnectionStatusResponse_msg
#define mouthware_message_PassThroughToMouthpadResponse_fields &mouthware_message_PassThroughToMouthpadResponse_msg
#define mouthware_message_PassThroughToApp_fields &mouthware_message_PassThroughToApp_msg
#define mouthware_message_RelayToAppMessage_fields &mouthware_message_RelayToAppMessage_msg

/* Maximum encoded size of messages (where known) */
#define MOUTHWARE_MESSAGE_MOUTHPADRELAY_PB_H_MAX_SIZE mouthware_message_RelayToAppMessage_size
#define mouthware_message_AppToRelayMessage_size 248
#define mouthware_message_BleConnectionStatusRead_size 0
#define mouthware_message_BleConnectionStatusResponse_size 13
#define mouthware_message_PassThroughToApp_size  258
#define mouthware_message_PassThroughToMouthpadResponse_size 2
#define mouthware_message_PassThroughToMouthpad_size 243
#define mouthware_message_RelayToAppMessage_size 261

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
