/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "MouthpadRelay.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mouthware_message_BleConnectionStatusRead, mouthware_message_BleConnectionStatusRead, AUTO)


PB_BIND(mouthware_message_DeviceInfoRead, mouthware_message_DeviceInfoRead, AUTO)


PB_BIND(mouthware_message_ClearBondsWrite, mouthware_message_ClearBondsWrite, AUTO)


PB_BIND(mouthware_message_DfuWrite, mouthware_message_DfuWrite, AUTO)


PB_BIND(mouthware_message_PassThroughToMouthpad, mouthware_message_PassThroughToMouthpad, AUTO)


PB_BIND(mouthware_message_AppToRelayMessage, mouthware_message_AppToRelayMessage, AUTO)


PB_BIND(mouthware_message_BleConnectionStatusResponse, mouthware_message_BleConnectionStatusResponse, AUTO)


PB_BIND(mouthware_message_DeviceInfoResponse, mouthware_message_DeviceInfoResponse, AUTO)


PB_BIND(mouthware_message_ClearBondsResponse, mouthware_message_ClearBondsResponse, AUTO)


PB_BIND(mouthware_message_DfuResponse, mouthware_message_DfuResponse, AUTO)


PB_BIND(mouthware_message_PassThroughToMouthpadResponse, mouthware_message_PassThroughToMouthpadResponse, AUTO)


PB_BIND(mouthware_message_PassThroughToApp, mouthware_message_PassThroughToApp, 2)


PB_BIND(mouthware_message_RelayToAppMessage, mouthware_message_RelayToAppMessage, 2)









