/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MOUTHWARE_MESSAGE_MOUTHPADRELAY_PB_H_INCLUDED
#define PB_MOUTHWARE_MESSAGE_MOUTHPADRELAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _mouthware_message_AppToRelayMessageDestination {
    mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_UNSPECIFIED = 0,
    mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_RELAY = 1,
    mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_MOUTHPAD = 2
} mouthware_message_AppToRelayMessageDestination;

typedef enum _mouthware_message_RelayBleConnectionStatus {
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_UNSPECIFIED = 0,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_DISCONNECTED = 1,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTED = 2,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_SEARCHING = 3,
    mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTING = 4
} mouthware_message_RelayBleConnectionStatus;

typedef enum _mouthware_message_DeviceFamily {
    mouthware_message_DeviceFamily_DEVICE_FAMILY_UNSPECIFIED = 0,
    mouthware_message_DeviceFamily_DEVICE_FAMILY_NRF = 1,
    mouthware_message_DeviceFamily_DEVICE_FAMILY_ESP = 2
} mouthware_message_DeviceFamily;

typedef enum _mouthware_message_DeviceBoard {
    mouthware_message_DeviceBoard_DEVICE_BOARD_UNSPECIFIED = 0,
    /* nRF52840 boards */
    mouthware_message_DeviceBoard_DEVICE_BOARD_SEEED_XIAO_NRF52840 = 1,
    mouthware_message_DeviceBoard_DEVICE_BOARD_NORDIC_NRF52840DONGLE = 2,
    mouthware_message_DeviceBoard_DEVICE_BOARD_APRBROTHER_NRF52840 = 3,
    mouthware_message_DeviceBoard_DEVICE_BOARD_RAYTAC_MDBT50Q_RX = 4,
    mouthware_message_DeviceBoard_DEVICE_BOARD_RAYTAC_MDBT50Q_CX_40 = 5,
    mouthware_message_DeviceBoard_DEVICE_BOARD_MAKERDIARY_NRF52840_MDK = 6,
    mouthware_message_DeviceBoard_DEVICE_BOARD_ADAFRUIT_FEATHER_NRF52840 = 7,
    /* ESP32-S3 boards */
    mouthware_message_DeviceBoard_DEVICE_BOARD_SEEED_XIAO_ESP32S3 = 100,
    mouthware_message_DeviceBoard_DEVICE_BOARD_LILYGO_TDISPLAY_S3 = 101
} mouthware_message_DeviceBoard;

typedef enum _mouthware_message_PassThroughToMouthpadErrorCode {
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNSPECIFIED = 0,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_TIMEOUT = 1,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_MESSAGE_TOO_LARGE = 2,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_MESSAGE_NOT_CONNECTED = 3,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNKNOWN_ERROR = 4,
    mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE = 5
} mouthware_message_PassThroughToMouthpadErrorCode;

/* Struct definitions */
typedef struct _mouthware_message_BleConnectionStatusRead {
    char dummy_field;
} mouthware_message_BleConnectionStatusRead;

typedef struct _mouthware_message_DeviceInfoRead {
    char dummy_field;
} mouthware_message_DeviceInfoRead;

typedef struct _mouthware_message_ClearBondsWrite {
    char dummy_field;
} mouthware_message_ClearBondsWrite;

typedef struct _mouthware_message_DfuWrite { /* Triggers device to enter bootloader/DFU mode */
    char dummy_field;
} mouthware_message_DfuWrite;

typedef struct _mouthware_message_ClearFirmwareCacheWrite { /* Clears cached firmware versions for all bonded devices
 Used when initiating firmware update to prevent false "update needed" warnings */
    char dummy_field;
} mouthware_message_ClearFirmwareCacheWrite;

typedef PB_BYTES_ARRAY_T(240) mouthware_message_PassThroughToMouthpad_data_t;
typedef struct _mouthware_message_PassThroughToMouthpad {
    mouthware_message_PassThroughToMouthpad_data_t data;
} mouthware_message_PassThroughToMouthpad;

/* / Message from App to the MouthPad Relay. */
typedef struct _mouthware_message_AppToRelayMessage {
    /* / The intended destination for the wrapped message. */
    mouthware_message_AppToRelayMessageDestination destination;
    pb_size_t which_message_body;
    union _mouthware_message_AppToRelayMessage_message_body {
        /* / Request information from the relay regarding current BLE connection status */
        mouthware_message_BleConnectionStatusRead ble_connection_status_read;
        /* / Message to forward to the MouthPad through the Relay. */
        mouthware_message_PassThroughToMouthpad pass_through_to_mouthpad;
        /* / Request device information from the connected MouthPad */
        mouthware_message_DeviceInfoRead device_info_read;
        /* / Request to clear all bonded devices on the relay */
        mouthware_message_ClearBondsWrite clear_bonds_write;
        /* / Request to enter DFU/bootloader mode */
        mouthware_message_DfuWrite dfu_write;
        /* / Request to clear cached firmware versions from relay */
        mouthware_message_ClearFirmwareCacheWrite clear_firmware_cache_write;
    } message_body;
} mouthware_message_AppToRelayMessage;

typedef struct _mouthware_message_BleConnectionStatusResponse {
    mouthware_message_RelayBleConnectionStatus connection_status;
    int32_t rssi;
    uint32_t battery_level; /* Battery level percentage (0-100) from BLE Battery Service */
} mouthware_message_BleConnectionStatusResponse;

typedef struct _mouthware_message_DeviceInfoResponse {
    pb_callback_t name; /* Advertised device name */
    pb_callback_t firmware; /* Firmware version */
    pb_callback_t address; /* BLE MAC address */
    uint32_t vid; /* USB Vendor ID from PnP ID characteristic */
    uint32_t pid; /* USB Product ID from PnP ID characteristic */
    mouthware_message_DeviceFamily family; /* Device family */
    mouthware_message_DeviceBoard board; /* Target board */
} mouthware_message_DeviceInfoResponse;

typedef struct _mouthware_message_ClearBondsResponse {
    bool success;
} mouthware_message_ClearBondsResponse;

typedef struct _mouthware_message_DfuResponse {
    bool success;
} mouthware_message_DfuResponse;

typedef struct _mouthware_message_ClearFirmwareCacheResponse {
    bool success;
} mouthware_message_ClearFirmwareCacheResponse;

typedef struct _mouthware_message_PassThroughToMouthpadResponse {
    mouthware_message_PassThroughToMouthpadErrorCode error_code;
} mouthware_message_PassThroughToMouthpadResponse;

typedef PB_BYTES_ARRAY_T(255) mouthware_message_PassThroughToApp_data_t;
typedef struct _mouthware_message_PassThroughToApp {
    mouthware_message_PassThroughToApp_data_t data;
} mouthware_message_PassThroughToApp;

/* / Message from the MouthPad Relay to the App. */
typedef struct _mouthware_message_RelayToAppMessage {
    pb_size_t which_message_body;
    union _mouthware_message_RelayToAppMessage_message_body {
        /* / Response to a BleConnectionStatusRead */
        mouthware_message_BleConnectionStatusResponse ble_connection_status_response;
        /* / Response to a PassThroughToMouthPadRequest (originating at the MouthPad). */
        mouthware_message_PassThroughToMouthpadResponse pass_through_to_mouthpad_response;
        /* / Message from the MouthPad for the app. */
        mouthware_message_PassThroughToApp pass_through_to_app;
        /* / Response to a DeviceInfoRead */
        mouthware_message_DeviceInfoResponse device_info_response;
        /* / Response to a ClearBondsWrite */
        mouthware_message_ClearBondsResponse clear_bonds_response;
        /* / Response to a DfuWrite */
        mouthware_message_DfuResponse dfu_response;
        /* / Response to a ClearFirmwareCacheWrite */
        mouthware_message_ClearFirmwareCacheResponse clear_firmware_cache_response;
    } message_body;
} mouthware_message_RelayToAppMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _mouthware_message_AppToRelayMessageDestination_MIN mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_UNSPECIFIED
#define _mouthware_message_AppToRelayMessageDestination_MAX mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_MOUTHPAD
#define _mouthware_message_AppToRelayMessageDestination_ARRAYSIZE ((mouthware_message_AppToRelayMessageDestination)(mouthware_message_AppToRelayMessageDestination_APP_RELAY_MESSAGE_DESTINATION_MOUTHPAD+1))

#define _mouthware_message_RelayBleConnectionStatus_MIN mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_UNSPECIFIED
#define _mouthware_message_RelayBleConnectionStatus_MAX mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTING
#define _mouthware_message_RelayBleConnectionStatus_ARRAYSIZE ((mouthware_message_RelayBleConnectionStatus)(mouthware_message_RelayBleConnectionStatus_RELAY_CONNECTION_STATUS_CONNECTING+1))

#define _mouthware_message_DeviceFamily_MIN mouthware_message_DeviceFamily_DEVICE_FAMILY_UNSPECIFIED
#define _mouthware_message_DeviceFamily_MAX mouthware_message_DeviceFamily_DEVICE_FAMILY_ESP
#define _mouthware_message_DeviceFamily_ARRAYSIZE ((mouthware_message_DeviceFamily)(mouthware_message_DeviceFamily_DEVICE_FAMILY_ESP+1))

#define _mouthware_message_DeviceBoard_MIN mouthware_message_DeviceBoard_DEVICE_BOARD_UNSPECIFIED
#define _mouthware_message_DeviceBoard_MAX mouthware_message_DeviceBoard_DEVICE_BOARD_LILYGO_TDISPLAY_S3
#define _mouthware_message_DeviceBoard_ARRAYSIZE ((mouthware_message_DeviceBoard)(mouthware_message_DeviceBoard_DEVICE_BOARD_LILYGO_TDISPLAY_S3+1))

#define _mouthware_message_PassThroughToMouthpadErrorCode_MIN mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_UNSPECIFIED
#define _mouthware_message_PassThroughToMouthpadErrorCode_MAX mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE
#define _mouthware_message_PassThroughToMouthpadErrorCode_ARRAYSIZE ((mouthware_message_PassThroughToMouthpadErrorCode)(mouthware_message_PassThroughToMouthpadErrorCode_PASS_THROUGH_TO_MOUTHPAD_ERROR_CODE_INVALID_MESSAGE+1))







#define mouthware_message_AppToRelayMessage_destination_ENUMTYPE mouthware_message_AppToRelayMessageDestination

#define mouthware_message_BleConnectionStatusResponse_connection_status_ENUMTYPE mouthware_message_RelayBleConnectionStatus

#define mouthware_message_DeviceInfoResponse_family_ENUMTYPE mouthware_message_DeviceFamily
#define mouthware_message_DeviceInfoResponse_board_ENUMTYPE mouthware_message_DeviceBoard




#define mouthware_message_PassThroughToMouthpadResponse_error_code_ENUMTYPE mouthware_message_PassThroughToMouthpadErrorCode




/* Initializer values for message structs */
#define mouthware_message_BleConnectionStatusRead_init_default {0}
#define mouthware_message_DeviceInfoRead_init_default {0}
#define mouthware_message_ClearBondsWrite_init_default {0}
#define mouthware_message_DfuWrite_init_default  {0}
#define mouthware_message_ClearFirmwareCacheWrite_init_default {0}
#define mouthware_message_PassThroughToMouthpad_init_default {{0, {0}}}
#define mouthware_message_AppToRelayMessage_init_default {_mouthware_message_AppToRelayMessageDestination_MIN, 0, {mouthware_message_BleConnectionStatusRead_init_default}}
#define mouthware_message_BleConnectionStatusResponse_init_default {_mouthware_message_RelayBleConnectionStatus_MIN, 0, 0}
#define mouthware_message_DeviceInfoResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, _mouthware_message_DeviceFamily_MIN, _mouthware_message_DeviceBoard_MIN}
#define mouthware_message_ClearBondsResponse_init_default {0}
#define mouthware_message_DfuResponse_init_default {0}
#define mouthware_message_ClearFirmwareCacheResponse_init_default {0}
#define mouthware_message_PassThroughToMouthpadResponse_init_default {_mouthware_message_PassThroughToMouthpadErrorCode_MIN}
#define mouthware_message_PassThroughToApp_init_default {{0, {0}}}
#define mouthware_message_RelayToAppMessage_init_default {0, {mouthware_message_BleConnectionStatusResponse_init_default}}
#define mouthware_message_BleConnectionStatusRead_init_zero {0}
#define mouthware_message_DeviceInfoRead_init_zero {0}
#define mouthware_message_ClearBondsWrite_init_zero {0}
#define mouthware_message_DfuWrite_init_zero     {0}
#define mouthware_message_ClearFirmwareCacheWrite_init_zero {0}
#define mouthware_message_PassThroughToMouthpad_init_zero {{0, {0}}}
#define mouthware_message_AppToRelayMessage_init_zero {_mouthware_message_AppToRelayMessageDestination_MIN, 0, {mouthware_message_BleConnectionStatusRead_init_zero}}
#define mouthware_message_BleConnectionStatusResponse_init_zero {_mouthware_message_RelayBleConnectionStatus_MIN, 0, 0}
#define mouthware_message_DeviceInfoResponse_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, _mouthware_message_DeviceFamily_MIN, _mouthware_message_DeviceBoard_MIN}
#define mouthware_message_ClearBondsResponse_init_zero {0}
#define mouthware_message_DfuResponse_init_zero  {0}
#define mouthware_message_ClearFirmwareCacheResponse_init_zero {0}
#define mouthware_message_PassThroughToMouthpadResponse_init_zero {_mouthware_message_PassThroughToMouthpadErrorCode_MIN}
#define mouthware_message_PassThroughToApp_init_zero {{0, {0}}}
#define mouthware_message_RelayToAppMessage_init_zero {0, {mouthware_message_BleConnectionStatusResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define mouthware_message_PassThroughToMouthpad_data_tag 1
#define mouthware_message_AppToRelayMessage_destination_tag 1
#define mouthware_message_AppToRelayMessage_ble_connection_status_read_tag 2
#define mouthware_message_AppToRelayMessage_pass_through_to_mouthpad_tag 3
#define mouthware_message_AppToRelayMessage_device_info_read_tag 4
#define mouthware_message_AppToRelayMessage_clear_bonds_write_tag 5
#define mouthware_message_AppToRelayMessage_dfu_write_tag 6
#define mouthware_message_AppToRelayMessage_clear_firmware_cache_write_tag 7
#define mouthware_message_BleConnectionStatusResponse_connection_status_tag 1
#define mouthware_message_BleConnectionStatusResponse_rssi_tag 2
#define mouthware_message_BleConnectionStatusResponse_battery_level_tag 3
#define mouthware_message_DeviceInfoResponse_name_tag 1
#define mouthware_message_DeviceInfoResponse_firmware_tag 2
#define mouthware_message_DeviceInfoResponse_address_tag 3
#define mouthware_message_DeviceInfoResponse_vid_tag 4
#define mouthware_message_DeviceInfoResponse_pid_tag 5
#define mouthware_message_DeviceInfoResponse_family_tag 6
#define mouthware_message_DeviceInfoResponse_board_tag 7
#define mouthware_message_ClearBondsResponse_success_tag 1
#define mouthware_message_DfuResponse_success_tag 1
#define mouthware_message_ClearFirmwareCacheResponse_success_tag 1
#define mouthware_message_PassThroughToMouthpadResponse_error_code_tag 1
#define mouthware_message_PassThroughToApp_data_tag 1
#define mouthware_message_RelayToAppMessage_ble_connection_status_response_tag 1
#define mouthware_message_RelayToAppMessage_pass_through_to_mouthpad_response_tag 2
#define mouthware_message_RelayToAppMessage_pass_through_to_app_tag 3
#define mouthware_message_RelayToAppMessage_device_info_response_tag 4
#define mouthware_message_RelayToAppMessage_clear_bonds_response_tag 5
#define mouthware_message_RelayToAppMessage_dfu_response_tag 6
#define mouthware_message_RelayToAppMessage_clear_firmware_cache_response_tag 7

/* Struct field encoding specification for nanopb */
#define mouthware_message_BleConnectionStatusRead_FIELDLIST(X, a) \

#define mouthware_message_BleConnectionStatusRead_CALLBACK NULL
#define mouthware_message_BleConnectionStatusRead_DEFAULT NULL

#define mouthware_message_DeviceInfoRead_FIELDLIST(X, a) \

#define mouthware_message_DeviceInfoRead_CALLBACK NULL
#define mouthware_message_DeviceInfoRead_DEFAULT NULL

#define mouthware_message_ClearBondsWrite_FIELDLIST(X, a) \

#define mouthware_message_ClearBondsWrite_CALLBACK NULL
#define mouthware_message_ClearBondsWrite_DEFAULT NULL

#define mouthware_message_DfuWrite_FIELDLIST(X, a) \

#define mouthware_message_DfuWrite_CALLBACK NULL
#define mouthware_message_DfuWrite_DEFAULT NULL

#define mouthware_message_ClearFirmwareCacheWrite_FIELDLIST(X, a) \

#define mouthware_message_ClearFirmwareCacheWrite_CALLBACK NULL
#define mouthware_message_ClearFirmwareCacheWrite_DEFAULT NULL

#define mouthware_message_PassThroughToMouthpad_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define mouthware_message_PassThroughToMouthpad_CALLBACK NULL
#define mouthware_message_PassThroughToMouthpad_DEFAULT NULL

#define mouthware_message_AppToRelayMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    destination,       1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,ble_connection_status_read,message_body.ble_connection_status_read),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_mouthpad,message_body.pass_through_to_mouthpad),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,device_info_read,message_body.device_info_read),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,clear_bonds_write,message_body.clear_bonds_write),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,dfu_write,message_body.dfu_write),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,clear_firmware_cache_write,message_body.clear_firmware_cache_write),   7)
#define mouthware_message_AppToRelayMessage_CALLBACK NULL
#define mouthware_message_AppToRelayMessage_DEFAULT NULL
#define mouthware_message_AppToRelayMessage_message_body_ble_connection_status_read_MSGTYPE mouthware_message_BleConnectionStatusRead
#define mouthware_message_AppToRelayMessage_message_body_pass_through_to_mouthpad_MSGTYPE mouthware_message_PassThroughToMouthpad
#define mouthware_message_AppToRelayMessage_message_body_device_info_read_MSGTYPE mouthware_message_DeviceInfoRead
#define mouthware_message_AppToRelayMessage_message_body_clear_bonds_write_MSGTYPE mouthware_message_ClearBondsWrite
#define mouthware_message_AppToRelayMessage_message_body_dfu_write_MSGTYPE mouthware_message_DfuWrite
#define mouthware_message_AppToRelayMessage_message_body_clear_firmware_cache_write_MSGTYPE mouthware_message_ClearFirmwareCacheWrite

#define mouthware_message_BleConnectionStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    connection_status,   1) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              2) \
X(a, STATIC,   SINGULAR, UINT32,   battery_level,     3)
#define mouthware_message_BleConnectionStatusResponse_CALLBACK NULL
#define mouthware_message_BleConnectionStatusResponse_DEFAULT NULL

#define mouthware_message_DeviceInfoResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   firmware,          2) \
X(a, CALLBACK, SINGULAR, STRING,   address,           3) \
X(a, STATIC,   SINGULAR, UINT32,   vid,               4) \
X(a, STATIC,   SINGULAR, UINT32,   pid,               5) \
X(a, STATIC,   SINGULAR, UENUM,    family,            6) \
X(a, STATIC,   SINGULAR, UENUM,    board,             7)
#define mouthware_message_DeviceInfoResponse_CALLBACK pb_default_field_callback
#define mouthware_message_DeviceInfoResponse_DEFAULT NULL

#define mouthware_message_ClearBondsResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define mouthware_message_ClearBondsResponse_CALLBACK NULL
#define mouthware_message_ClearBondsResponse_DEFAULT NULL

#define mouthware_message_DfuResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define mouthware_message_DfuResponse_CALLBACK NULL
#define mouthware_message_DfuResponse_DEFAULT NULL

#define mouthware_message_ClearFirmwareCacheResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define mouthware_message_ClearFirmwareCacheResponse_CALLBACK NULL
#define mouthware_message_ClearFirmwareCacheResponse_DEFAULT NULL

#define mouthware_message_PassThroughToMouthpadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        1)
#define mouthware_message_PassThroughToMouthpadResponse_CALLBACK NULL
#define mouthware_message_PassThroughToMouthpadResponse_DEFAULT NULL

#define mouthware_message_PassThroughToApp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define mouthware_message_PassThroughToApp_CALLBACK NULL
#define mouthware_message_PassThroughToApp_DEFAULT NULL

#define mouthware_message_RelayToAppMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,ble_connection_status_response,message_body.ble_connection_status_response),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_mouthpad_response,message_body.pass_through_to_mouthpad_response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,pass_through_to_app,message_body.pass_through_to_app),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,device_info_response,message_body.device_info_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,clear_bonds_response,message_body.clear_bonds_response),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,dfu_response,message_body.dfu_response),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_body,clear_firmware_cache_response,message_body.clear_firmware_cache_response),   7)
#define mouthware_message_RelayToAppMessage_CALLBACK NULL
#define mouthware_message_RelayToAppMessage_DEFAULT NULL
#define mouthware_message_RelayToAppMessage_message_body_ble_connection_status_response_MSGTYPE mouthware_message_BleConnectionStatusResponse
#define mouthware_message_RelayToAppMessage_message_body_pass_through_to_mouthpad_response_MSGTYPE mouthware_message_PassThroughToMouthpadResponse
#define mouthware_message_RelayToAppMessage_message_body_pass_through_to_app_MSGTYPE mouthware_message_PassThroughToApp
#define mouthware_message_RelayToAppMessage_message_body_device_info_response_MSGTYPE mouthware_message_DeviceInfoResponse
#define mouthware_message_RelayToAppMessage_message_body_clear_bonds_response_MSGTYPE mouthware_message_ClearBondsResponse
#define mouthware_message_RelayToAppMessage_message_body_dfu_response_MSGTYPE mouthware_message_DfuResponse
#define mouthware_message_RelayToAppMessage_message_body_clear_firmware_cache_response_MSGTYPE mouthware_message_ClearFirmwareCacheResponse

extern const pb_msgdesc_t mouthware_message_BleConnectionStatusRead_msg;
extern const pb_msgdesc_t mouthware_message_DeviceInfoRead_msg;
extern const pb_msgdesc_t mouthware_message_ClearBondsWrite_msg;
extern const pb_msgdesc_t mouthware_message_DfuWrite_msg;
extern const pb_msgdesc_t mouthware_message_ClearFirmwareCacheWrite_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToMouthpad_msg;
extern const pb_msgdesc_t mouthware_message_AppToRelayMessage_msg;
extern const pb_msgdesc_t mouthware_message_BleConnectionStatusResponse_msg;
extern const pb_msgdesc_t mouthware_message_DeviceInfoResponse_msg;
extern const pb_msgdesc_t mouthware_message_ClearBondsResponse_msg;
extern const pb_msgdesc_t mouthware_message_DfuResponse_msg;
extern const pb_msgdesc_t mouthware_message_ClearFirmwareCacheResponse_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToMouthpadResponse_msg;
extern const pb_msgdesc_t mouthware_message_PassThroughToApp_msg;
extern const pb_msgdesc_t mouthware_message_RelayToAppMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define mouthware_message_BleConnectionStatusRead_fields &mouthware_message_BleConnectionStatusRead_msg
#define mouthware_message_DeviceInfoRead_fields &mouthware_message_DeviceInfoRead_msg
#define mouthware_message_ClearBondsWrite_fields &mouthware_message_ClearBondsWrite_msg
#define mouthware_message_DfuWrite_fields &mouthware_message_DfuWrite_msg
#define mouthware_message_ClearFirmwareCacheWrite_fields &mouthware_message_ClearFirmwareCacheWrite_msg
#define mouthware_message_PassThroughToMouthpad_fields &mouthware_message_PassThroughToMouthpad_msg
#define mouthware_message_AppToRelayMessage_fields &mouthware_message_AppToRelayMessage_msg
#define mouthware_message_BleConnectionStatusResponse_fields &mouthware_message_BleConnectionStatusResponse_msg
#define mouthware_message_DeviceInfoResponse_fields &mouthware_message_DeviceInfoResponse_msg
#define mouthware_message_ClearBondsResponse_fields &mouthware_message_ClearBondsResponse_msg
#define mouthware_message_DfuResponse_fields &mouthware_message_DfuResponse_msg
#define mouthware_message_ClearFirmwareCacheResponse_fields &mouthware_message_ClearFirmwareCacheResponse_msg
#define mouthware_message_PassThroughToMouthpadResponse_fields &mouthware_message_PassThroughToMouthpadResponse_msg
#define mouthware_message_PassThroughToApp_fields &mouthware_message_PassThroughToApp_msg
#define mouthware_message_RelayToAppMessage_fields &mouthware_message_RelayToAppMessage_msg

/* Maximum encoded size of messages (where known) */
/* mouthware_message_DeviceInfoResponse_size depends on runtime parameters */
/* mouthware_message_RelayToAppMessage_size depends on runtime parameters */
#define MOUTHWARE_MESSAGE_MOUTHPADRELAY_PB_H_MAX_SIZE mouthware_message_PassThroughToApp_size
#define mouthware_message_AppToRelayMessage_size 248
#define mouthware_message_BleConnectionStatusRead_size 0
#define mouthware_message_BleConnectionStatusResponse_size 19
#define mouthware_message_ClearBondsResponse_size 2
#define mouthware_message_ClearBondsWrite_size   0
#define mouthware_message_ClearFirmwareCacheResponse_size 2
#define mouthware_message_ClearFirmwareCacheWrite_size 0
#define mouthware_message_DeviceInfoRead_size    0
#define mouthware_message_DfuResponse_size       2
#define mouthware_message_DfuWrite_size          0
#define mouthware_message_PassThroughToApp_size  258
#define mouthware_message_PassThroughToMouthpadResponse_size 2
#define mouthware_message_PassThroughToMouthpad_size 243

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
